# Site settings
title: RIDVAN KARABUDAK
email: karabudakrdvan@yahoo.com.tr
description: > # this means to ignore newlines until "baseurl:"
  Computer Engineer,Turkey
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  RKarabudak
google_username: Rıdvan

permalink: /:categories/:title

links:
  -title: about
  url : /about
  -title: work
  url : /work
  -title: articles
  url : /articles
  -title: abilities
  url : /abilities

# Build settings
markdown: kramdown
 